from qickit.circuit import Circuit

__all__ = ["MCRX", "MCRY", "MCRZ"]

def MCRX(circuit: Circuit, theta: float, control_indices: list[int], target_index: int) -> None: ...
def MCRY(circuit: Circuit, theta: float, control_indices: list[int], target_index: int) -> None: ...
def MCRZ(circuit: Circuit, theta: float, control_indices: list[int], target_index: int) -> None: ...
