from _typeshed import Incomplete

__all__ = ['DAGNode']

class DAGNode:
    name: Incomplete
    children: Incomplete
    def __init__(self, name: str) -> None: ...
    def to(self, next: DAGNode) -> None: ...
    def generate_paths(self) -> list[list[str]]: ...
    def get_depth(self) -> int: ...
    def __eq__(self, value: object) -> bool: ...
